// Clock Canvas Web - Code Generation Service
// REQ-CG-001 (Verilog RTL), REQ-CG-002 (SDC), REQ-CG-003 (incomplete design),
// REQ-CG-009 (Verilog syntax), REQ-CG-010 (SDC syntax), REQ-CG-011 (empty design)

import type Database from 'better-sqlite3';
import type {
  ClockNode,
  ClockEdge,
  ComponentType,
  IncompleteItem,
} from '../models/types.js';
import { parsePort } from '../models/types.js';
import { buildGraph, propagateFrequencies, analyzeCDC } from './clock-tree.js';

// ==================== Design Validation (REQ-CG-003, REQ-CG-011) ====================

export function validateDesignCompleteness(
  db: Database.Database,
  projectId: string,
): IncompleteItem[] {
  const items: IncompleteItem[] = [];

  const nodeRows = db.prepare(
    'SELECT id, type, properties FROM nodes WHERE project_id = ?'
  ).all(projectId) as Array<{ id: string; type: ComponentType; properties: string }>;

  if (nodeRows.length === 0) {
    return []; // Empty design handled separately by caller
  }

  const edgeRows = db.prepare(
    'SELECT source, target FROM edges WHERE project_id = ?'
  ).all(projectId) as Array<{ source: string; target: string }>;

  // Build set of connected input ports
  const connectedInputPorts = new Set<string>();
  for (const edge of edgeRows) {
    connectedInputPorts.add(edge.target);
  }

  for (const row of nodeRows) {
    const props = JSON.parse(row.properties) as Record<string, unknown>;

    switch (row.type) {
      case 'PLL': {
        if (props.output_freq === undefined || props.output_freq === null) {
          items.push({ node_id: row.id, node_type: row.type, reason: 'Missing required property: output_freq' });
        }
        break;
      }
      case 'Divider': {
        if (props.ratio === undefined || props.ratio === null) {
          items.push({ node_id: row.id, node_type: row.type, reason: 'Missing required property: ratio' });
        }
        if (!connectedInputPorts.has(`${row.id}:in`)) {
          items.push({ node_id: row.id, node_type: row.type, reason: 'Unconnected input port' });
        }
        break;
      }
      case 'Mux': {
        if (props.select_index === undefined || props.select_index === null) {
          items.push({ node_id: row.id, node_type: row.type, reason: 'Missing required property: select_index' });
        } else {
          // Check if select_index is within range of connected inputs
          let maxConnectedIdx = -1;
          for (const edge of edgeRows) {
            const tgt = parsePort(edge.target);
            if (tgt.nodeId === row.id && tgt.portName.startsWith('in_')) {
              const idx = parseInt(tgt.portName.substring(3), 10);
              if (!isNaN(idx) && idx > maxConnectedIdx) maxConnectedIdx = idx;
            }
          }
          if (maxConnectedIdx === -1) {
            items.push({ node_id: row.id, node_type: row.type, reason: 'No connected inputs' });
          } else if ((props.select_index as number) > maxConnectedIdx) {
            items.push({
              node_id: row.id,
              node_type: row.type,
              reason: `select_index ${props.select_index} out of range (max connected: ${maxConnectedIdx})`,
            });
          }
        }
        break;
      }
      case 'ClockGate':
      case 'ClockDomain':
      case 'IPBlock': {
        if (!connectedInputPorts.has(`${row.id}:in`)) {
          items.push({ node_id: row.id, node_type: row.type, reason: 'Unconnected input port' });
        }
        break;
      }
    }
  }

  return items;
}

// ==================== Verilog RTL Generation (REQ-CG-001, REQ-CG-009) ====================

export function generateRTL(
  db: Database.Database,
  projectId: string,
  projectName: string,
): string {
  const graph = buildGraph(db, projectId);
  propagateFrequencies(graph);

  const moduleName = sanitizeName(projectName);
  const timestamp = new Date().toISOString();

  const lines: string[] = [];

  // Header comment (Constraint 5: timestamp + project name)
  lines.push(`// Generated by Clock Canvas`);
  lines.push(`// Project: ${projectName}`);
  lines.push(`// Timestamp: ${timestamp}`);
  lines.push(`// IEEE 1364-2005 (Verilog-2005)`);
  lines.push(``);

  // Categorize nodes
  const plls: ClockNode[] = [];
  const dividers: ClockNode[] = [];
  const muxes: ClockNode[] = [];
  const gates: ClockNode[] = [];
  const domains: ClockNode[] = [];
  const ipBlocks: ClockNode[] = [];

  for (const node of graph.nodes.values()) {
    switch (node.type) {
      case 'PLL': plls.push(node); break;
      case 'Divider': dividers.push(node); break;
      case 'Mux': muxes.push(node); break;
      case 'ClockGate': gates.push(node); break;
      case 'ClockDomain': domains.push(node); break;
      case 'IPBlock': ipBlocks.push(node); break;
    }
  }

  // Build port lists
  const inputPorts: string[] = [];
  const outputPorts: string[] = [];

  // (a) PLL clock inputs
  for (const pll of plls) {
    inputPorts.push(`clk_${nodeName(pll)}`);
  }

  // (d) Clock Gate enable inputs
  for (const gate of gates) {
    inputPorts.push(`en_${nodeName(gate)}`);
  }

  // (c) Mux select inputs
  for (const mux of muxes) {
    inputPorts.push(`sel_${nodeName(mux)}`);
  }

  // (f) IP Block clock outputs
  for (const ip of ipBlocks) {
    outputPorts.push(`clk_${nodeName(ip)}`);
  }

  // Module declaration
  const allPorts = [
    ...inputPorts.map(p => `  input wire ${p}`),
    ...outputPorts.map(p => `  output wire ${p}`),
  ];

  lines.push(`module ${moduleName} (`);
  for (let i = 0; i < allPorts.length; i++) {
    lines.push(`${allPorts[i]}${i < allPorts.length - 1 ? ',' : ''}`);
  }
  lines.push(`);`);
  lines.push(``);

  // Wire declarations
  const wires: string[] = [];
  const regs: string[] = [];

  for (const pll of plls) {
    wires.push(`  wire clk_${nodeName(pll)}_out;`);
  }
  for (const div of dividers) {
    const ratio = div.properties.ratio || 2;
    const bits = Math.ceil(Math.log2(ratio));
    regs.push(`  reg [${bits - 1}:0] ${nodeName(div)}_counter;`);
    regs.push(`  reg clk_${nodeName(div)}_out;`);
  }
  for (const mux of muxes) {
    wires.push(`  wire clk_${nodeName(mux)}_out;`);
  }
  for (const gate of gates) {
    wires.push(`  wire clk_${nodeName(gate)}_out;`);
  }

  if (wires.length > 0) {
    lines.push(`  // Internal wires`);
    lines.push(...wires);
    lines.push(``);
  }
  if (regs.length > 0) {
    lines.push(`  // Registers`);
    lines.push(...regs);
    lines.push(``);
  }

  // (a) PLL: pass-through from input port
  for (const pll of plls) {
    const name = nodeName(pll);
    lines.push(`  // PLL: ${pll.properties.name || pll.id} (${pll.properties.output_freq || 0} MHz)`);
    lines.push(`  assign clk_${name}_out = clk_${name};`);
    lines.push(``);
  }

  // (b) Divider: always block with counter
  for (const div of dividers) {
    const name = nodeName(div);
    const ratio = div.properties.ratio || 2;
    const halfRatio = ratio / 2;
    const inputSrc = findInputSource(graph, div.id, 'in');
    const inputClk = inputSrc ? getSignalName(graph, inputSrc) : 'clk_unknown';

    lines.push(`  // Divider: ${div.properties.name || div.id} (ratio: ${ratio})`);
    lines.push(`  always @(posedge ${inputClk}) begin`);
    lines.push(`    if (${name}_counter == ${halfRatio - 1}) begin`);
    lines.push(`      ${name}_counter <= 0;`);
    lines.push(`      clk_${name}_out <= ~clk_${name}_out;`);
    lines.push(`    end else begin`);
    lines.push(`      ${name}_counter <= ${name}_counter + 1;`);
    lines.push(`    end`);
    lines.push(`  end`);
    lines.push(``);
  }

  // (c) Mux: assign with ternary operator
  for (const mux of muxes) {
    const name = nodeName(mux);
    const inputs = collectMuxInputs(graph, mux.id);

    lines.push(`  // Mux: ${mux.properties.name || mux.id}`);
    if (inputs.length === 2) {
      lines.push(`  assign clk_${name}_out = sel_${name} ? ${inputs[1]?.signal ?? "1'b0"} : ${inputs[0]?.signal ?? "1'b0"};`);
    } else if (inputs.length > 2) {
      let expr = inputs[0]?.signal ?? "1'b0";
      for (let i = 1; i < inputs.length; i++) {
        expr = `(sel_${name} == ${i}) ? ${inputs[i]?.signal ?? "1'b0"} : (${expr})`;
      }
      lines.push(`  assign clk_${name}_out = ${expr};`);
    } else if (inputs.length === 1) {
      lines.push(`  assign clk_${name}_out = ${inputs[0]?.signal ?? "1'b0"};`);
    }
    lines.push(``);
  }

  // (d) Clock Gate: AND gate with enable
  for (const gate of gates) {
    const name = nodeName(gate);
    const inputSrc = findInputSource(graph, gate.id, 'in');
    const inputClk = inputSrc ? getSignalName(graph, inputSrc) : 'clk_unknown';

    lines.push(`  // Clock Gate: ${gate.properties.name || gate.id}`);
    lines.push(`  assign clk_${name}_out = ${inputClk} & en_${name};`);
    lines.push(``);
  }

  // (e) Clock Domain boundary comments
  for (const domain of domains) {
    const domainName = domain.properties.domain_name || domain.properties.name || domain.id;
    lines.push(`  // ---- Clock Domain Boundary: ${domainName} ----`);
    lines.push(``);
  }

  // (f) IP Block: output assignments
  for (const ip of ipBlocks) {
    const name = nodeName(ip);
    const inputSrc = findInputSource(graph, ip.id, 'in');
    const inputClk = inputSrc ? getSignalName(graph, inputSrc) : 'clk_unknown';

    lines.push(`  // IP Block: ${ip.properties.name || ip.id}`);
    lines.push(`  assign clk_${name} = ${inputClk};`);
    lines.push(``);
  }

  lines.push(`endmodule`);
  return lines.join('\n');
}

// ==================== SDC Generation (REQ-CG-002, REQ-CG-010) ====================

export function generateSDC(
  db: Database.Database,
  projectId: string,
  projectName: string,
): string {
  const graph = buildGraph(db, projectId);
  propagateFrequencies(graph);
  const cdcCrossings = analyzeCDC(graph);

  const timestamp = new Date().toISOString();
  const lines: string[] = [];

  // Header (Constraint 5)
  lines.push(`# Generated by Clock Canvas`);
  lines.push(`# Project: ${projectName}`);
  lines.push(`# Timestamp: ${timestamp}`);
  lines.push(`# Synopsys Design Constraints (SDC)`);
  lines.push(``);

  // (a) create_clock for each PLL
  for (const node of graph.nodes.values()) {
    if (node.type === 'PLL') {
      const name = nodeName(node);
      const freq = node.properties.output_freq || 0;
      const period = freq > 0 ? (1000 / freq) : 0; // MHz -> ns
      lines.push(`create_clock -name clk_${name} -period ${period.toFixed(3)} [get_ports clk_${name}]`);
    }
  }
  lines.push(``);

  // (b) create_generated_clock for Dividers and Muxes
  for (const node of graph.nodes.values()) {
    if (node.type === 'Divider') {
      const name = nodeName(node);
      const ratio = node.properties.ratio || 2;
      const inputSrc = findInputSource(graph, node.id, 'in');
      const srcClkName = inputSrc ? `clk_${nodeName(graph.nodes.get(inputSrc)!)}` : 'clk_unknown';

      lines.push(`create_generated_clock -name clk_${name} -source [get_pins ${srcClkName}] -divide_by ${ratio} [get_pins clk_${name}_out]`);
    } else if (node.type === 'Mux') {
      const name = nodeName(node);
      const selIdx = node.properties.select_index ?? 0;
      const inputSrc = findInputSource(graph, node.id, `in_${selIdx}`);
      const srcClkName = inputSrc ? `clk_${nodeName(graph.nodes.get(inputSrc)!)}` : 'clk_unknown';

      lines.push(`create_generated_clock -name clk_${name} -source [get_pins ${srcClkName}] -divide_by 1 [get_pins clk_${name}_out]`);
    }
  }
  lines.push(``);

  // (c) set_clock_groups for Clock Domains with different frequencies
  const domainClocks = collectDomainClocks(graph);
  if (domainClocks.length > 1) {
    const groupArgs = domainClocks
      .map(dc => `-group [get_clocks ${dc.clocks.join(' ')}]`)
      .join(' ');
    lines.push(`set_clock_groups -asynchronous ${groupArgs}`);
    lines.push(``);
  }

  // (d) set_false_path for CDC crossings
  if (cdcCrossings.length > 0) {
    lines.push(`# CDC False Paths`);
    const uniquePairs = new Set<string>();
    for (const crossing of cdcCrossings) {
      const key = `${crossing.source_domain}|${crossing.target_domain}`;
      if (!uniquePairs.has(key)) {
        uniquePairs.add(key);
        const srcName = nodeName(graph.nodes.get(crossing.source_domain)!);
        const tgtName = nodeName(graph.nodes.get(crossing.target_domain)!);
        lines.push(`set_false_path -from [get_clocks clk_${srcName}*] -to [get_clocks clk_${tgtName}*]`);
      }
    }
  }

  return lines.join('\n');
}

// ==================== Helpers ====================

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
}

function nodeName(node: ClockNode): string {
  return sanitizeName(node.properties.name || `${node.type.toLowerCase()}_${node.id.substring(0, 8)}`);
}

function findInputSource(
  graph: { edges: Map<string, ClockEdge> },
  nodeId: string,
  portName: string,
): string | null {
  for (const edge of graph.edges.values()) {
    const tgt = parsePort(edge.target);
    if (tgt.nodeId === nodeId && tgt.portName === portName) {
      return parsePort(edge.source).nodeId;
    }
  }
  return null;
}

function getSignalName(
  graph: { nodes: Map<string, ClockNode> },
  nodeId: string,
): string {
  const node = graph.nodes.get(nodeId);
  if (!node) return 'clk_unknown';

  const name = nodeName(node);
  switch (node.type) {
    case 'PLL':
    case 'Divider':
    case 'Mux':
    case 'ClockGate':
      return `clk_${name}_out`;
    default:
      return `clk_${name}`;
  }
}

interface MuxInput {
  idx: number;
  signal: string;
}

function collectMuxInputs(
  graph: { nodes: Map<string, ClockNode>; edges: Map<string, ClockEdge> },
  muxNodeId: string,
): MuxInput[] {
  const inputs: MuxInput[] = [];
  for (const edge of graph.edges.values()) {
    const tgt = parsePort(edge.target);
    if (tgt.nodeId === muxNodeId && tgt.portName.startsWith('in_')) {
      const idx = parseInt(tgt.portName.substring(3), 10);
      if (!isNaN(idx)) {
        const srcNodeId = parsePort(edge.source).nodeId;
        inputs.push({ idx, signal: getSignalName(graph, srcNodeId) });
      }
    }
  }
  inputs.sort((a, b) => a.idx - b.idx);
  return inputs;
}

interface DomainClock {
  domainId: string;
  clocks: string[];
}

function collectDomainClocks(
  graph: { nodes: Map<string, ClockNode>; edges: Map<string, ClockEdge> },
): DomainClock[] {
  const result: DomainClock[] = [];

  for (const node of graph.nodes.values()) {
    if (node.type === 'ClockDomain') {
      const inputSrc = findInputSource(graph, node.id, 'in');
      if (inputSrc) {
        const srcNode = graph.nodes.get(inputSrc);
        if (srcNode) {
          result.push({
            domainId: node.id,
            clocks: [`clk_${nodeName(srcNode)}`],
          });
        }
      }
    }
  }

  return result;
}
